In [ ]:
import pandas as pd
import numpy as np

data=[
     ['John', 'Anna', 'Peter', 'Linda'],
     [28, 34, 29, 42],
     ['New York', 'Paris', 'Berlin', 'London'],
     [65000, 70000, 62000, 85000]
]
x = pd.DataFrame(data)
print(x)

          0      1       2       3
0      John   Anna   Peter   Linda
1        28     34      29      42
2  New York  Paris  Berlin  London
3     65000  70000   62000   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns=['name','age','city','salary']
y_1=pd.DataFrame(data_list,columns=columns)
y_1

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
print(y_1[['name','city']])

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [ ]:
y_1["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
y_1

    name  age      city  salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.